#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HEIGHT 648
#define WIDTH 864
#define DELAY 1 //ms
#define NB_MONSTRES 11
#define NB_BOUCLIERS 4
#define HAUTEUR_BOUCLIER 500
#define HAUTEUR_JOUEUR 600
#define MISSILES_COOLDOWN 500
#define BOMBS_COOLDOWN 500 // en ms
#define ANIMATION_TIMER 250
#define DECALAGE_MONSTRES_VERTICAL 50
#define DECALAGE_MONSTRES_HORIZONTAL 25
#define DELAY_JOUEUR 0
#define DELAY_MONSTRES 500
#define DELAY_MISSILES 1
#define DELAY_BOMBES 3
#define COOLDOWN_DEGATS 500

#endif
